# Tên của workflow
name: Java Backend Compilation

# Điều kiện kích hoạt workflow (khi có push hoặc pull request trên nhánh main)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Các công việc (jobs) trong workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Bước 1: Checkout mã nguồn
    - uses: actions/checkout@v4

    # Bước 2: Thiết lập Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Hoặc gradle nếu bạn dùng Gradle

    # Bước 3: Biên dịch (Compile) và Đóng gói (Package) mã nguồn
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
